title: trabaldini collection
email: emanuela@trabaldo.de
description: >- # this means to ignore newlines until "baseurl:"
  A portfolio of some projects and math stuff
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://trabaldo.de" # the base hostname & protocol for your site
twitter_username: trabaldini
github_username:  trabaldini

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
