title: trabaldini collection
email: emanuela@trabaldo.de
description: >- 
  A portfolio of some projects and math stuff

# SEO settings
lang: en
author:
  name: Emanuela Trabaldo Lena
  twitter: trabaldini
  github: trabaldini

# Build settings
markdown: kramdown
theme: minima
permalink: /blog/:year/:month/:day/:title/
sass:
  style: compressed
  sourcemap: never

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

# Optimization
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Performance
incremental: true
livereload: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-compress-images

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .git
  - .github
  - .DS_Store